title:            Cristian Molina Blog
description:      Cristian Molina website, currently studying web development.
url:              legomolina.github.io
signoff:          # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.
paginate: 10
paginate_path: "/page/:num"
links:
  - name:         Home
    url:          /
  - name:         About me
    url:          /about
  - name:         Email
    url:          mailto:legomolina@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/legomolina
    external:     true
highlighter:      rouge
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
